# Use an official OpenJDK runtime as a parent image
FROM ranyamh/currency-exchange-service:1.0.3

# Set the working directory inside the container
WORKDIR /app

# Copy the packaged jar file from the target directory to the app directory
COPY target/currency-exchange-service-0.0.1-SNAPSHOT.jar /app/exchange-service.jar

# Expose the port your application runs on
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/exchange-service.jar"]
